apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: segundo-pod
  ports:
    # Poderíamos definir só a port se a entrada e saída for a msm
    - port: 9000
    - targetPort: 80
